version: "3.7"

services:
    scraper:
        build:
            context: ./
            target: development-build-stage
        environment:
            WATCHPACK_POLLING: "true"
        volumes:
            - ./:/app
            - /app/node_modules
        restart: "unless-stopped"
        